### ISSUE TITLE
Unhandled exception in RatScanner v2.2.1.0

### ISSUE THREAD

**Issue by osumunbro** [Blightbuster/RatScanner#19]
**Error**
Unhandled exception in RatScanner v2.2.1.0
```
System.IO.IOException: The process cannot access the file 'C:\Users\Josh\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at RatScanner.IconManager.LoadDynamicCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
<details>
<summary>Log</summary>

```
[03:36:48.8492430] > [Info]  ----- RatScanner 2.2.1 -----
[03:36:48.8505791] > [Info]  Starting RatScanner...
[03:36:48.8509163] > [Info]  Loading config...
[03:36:48.8752674] > [Info]  Loading price data...
[03:36:49.5388789] > [Info]  Setting default item...
[03:36:49.5428939] > [Info]  Initializing name scan...
[03:36:49.5435699] > [Info]  Loading OCR data...
[03:36:49.9320590] > [Info]  Initializing icon scan...
[03:36:49.9345058] > [Info]  Loading static icons...
[03:36:50.0246332] > [Info]  Loaded 1141/1141 icons successfully.
[03:36:50.0251530] > [Info]  Loading dynamic icons...
[03:36:50.1773996] > [Info]  Loaded 1861/1861 icons successfully.
[03:36:50.1792490] > [Info]  Loading static correlation data...
[03:36:50.1877215] > [Info]  Loading dynamic correlation data...
[03:36:50.2133895] > [Info]  Initializing file watcher for icon cache...
[03:36:50.2153319] > [Info]  Prewarming name tool tip...
[03:36:50.4040975] > [Info]  Prewarming icon tool tip...
[03:36:50.4358644] > [Info]  Registering mouse and keyboard hooks...
[03:36:50.4375217] > [Info]  Ready!
[03:36:50.4402755] > [Info]  Loading resource "RSClientVersion"...
[03:36:50.6527132] > [Info]  Loading resource "RSPatreon"...
[03:36:50.7675098] > [Info]  Loading resource "RSDiscord"...
[03:36:50.8939598] > [Info]  Loading resource "RSGithub"...
[03:36:58.5056829] > [Info]  Loading dynamic icons...
[03:36:58.6164574] > [Info]  Loaded 1862/1862 icons successfully.
[03:36:58.6168289] > [Info]  Loading dynamic correlation data...
[03:36:58.6405945] > [Info]  Loading dynamic icons...
[03:36:58.7496644] > [Info]  Loaded 1863/1863 icons successfully.
[03:36:58.7500460] > [Info]  Loading dynamic correlation data...
[03:36:58.7830003] > [Info]  Loading dynamic icons...
[03:36:58.8897261] > [Info]  Loaded 1863/1863 icons successfully.
[03:36:58.8900861] > [Info]  Loading dynamic correlation data...
[03:36:58.9033609] > [Info]  Loading dynamic icons...
[03:36:59.0124067] > [Info]  Loaded 1863/1863 icons successfully.
[03:36:59.0128301] > [Info]  Loading dynamic correlation data...
[03:37:09.0400833] > [Info]  Loading dynamic icons...
[03:37:09.1519011] > [Info]  Loaded 1864/1864 icons successfully.
[03:37:09.1522996] > [Info]  Loading dynamic correlation data...
[03:37:09.1687716] > [Info]  Loading dynamic icons...
[03:37:09.2720005] > [Info]  Loaded 1864/1864 icons successfully.
[03:37:09.2723309] > [Info]  Loading dynamic correlation data...
[03:37:09.3222855] > [Info]  Loading dynamic icons...
[03:37:09.4315331] > [Info]  Loaded 1865/1865 icons successfully.
[03:37:09.4319127] > [Info]  Loading dynamic correlation data...
[03:37:09.4518297] > [Info]  Loading dynamic icons...
[03:37:09.5741636] > [Info]  Loaded 1866/1866 icons successfully.
[03:37:09.5748577] > [Info]  Loading dynamic correlation data...
[03:37:09.5885071] > [Info]  Loading dynamic icons...
[03:37:09.6970738] > [Info]  Loaded 1866/1866 icons successfully.
[03:37:09.6974561] > [Info]  Loading dynamic correlation data...
[03:37:09.7260538] > [Error] Unhandled exception in RatScanner v2.2.1.0
 -------------------- 
 System.IO.IOException: The process cannot access the file 'C:\Users\Josh\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at RatScanner.IconManager.LoadDynamicCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
</details>

**Comment by Blightbuster** [comment]
Fix will be merged into master when next release is ready.
