### ISSUE TITLE
Unhandled exception in RatScanner v2.2.1.0

### ISSUE THREAD

**Issue by Shaunieboy** [Blightbuster/RatScanner#22]
**Error**
Unhandled exception in RatScanner v2.2.1.0
```
System.IO.IOException: The process cannot access the file 'C:\Users\shaun\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at RatScanner.IconManager.LoadDynamicCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
<details>
<summary>Log</summary>

```
[11:53:24.9830597] > [Info]  ----- RatScanner 2.2.1 -----
[11:53:24.9846139] > [Info]  Starting RatScanner...
[11:53:24.9850104] > [Info]  Loading config...
[11:53:25.1227618] > [Info]  Loading price data...
[11:53:26.0671130] > [Info]  Setting default item...
[11:53:26.0747260] > [Info]  Initializing name scan...
[11:53:26.0760592] > [Info]  Loading OCR data...
[11:53:26.4150352] > [Info]  Initializing icon scan...
[11:53:26.4253456] > [Info]  Loading static icons...
[11:53:28.0750944] > [Info]  Loaded 1141/1141 icons successfully.
[11:53:28.0762184] > [Info]  Loading dynamic icons...
[11:53:28.0920704] > [Info]  Loaded 60/60 icons successfully.
[11:53:28.0949377] > [Info]  Loading static correlation data...
[11:53:28.1138633] > [Info]  Loading dynamic correlation data...
[11:53:28.1310365] > [Info]  Initializing file watcher for icon cache...
[11:53:28.1336805] > [Info]  Prewarming name tool tip...
[11:53:28.5279973] > [Info]  Prewarming icon tool tip...
[11:53:28.6424666] > [Info]  Registering mouse and keyboard hooks...
[11:53:28.6456552] > [Info]  Ready!
[11:53:28.6500484] > [Info]  Loading resource "RSClientVersion"...
[11:53:29.0332340] > [Info]  Loading resource "RSPatreon"...
[11:53:29.3139834] > [Info]  Loading resource "RSDiscord"...
[11:53:29.5939110] > [Info]  Loading resource "RSGithub"...
[12:03:00.9727874] > [Info]  Loading dynamic icons...
[12:03:01.0551007] > [Info]  Loaded 61/61 icons successfully.
[12:03:01.0558875] > [Info]  Loading dynamic correlation data...
[12:03:01.0578513] > [Info]  Loading dynamic icons...
[12:03:01.0637427] > [Info]  Loaded 61/61 icons successfully.
[12:03:01.0645399] > [Info]  Loading dynamic correlation data...
[12:05:53.0056912] > [Info]  Loading dynamic icons...
[12:05:53.0112851] > [Info]  Loaded 62/62 icons successfully.
[12:05:53.0120798] > [Info]  Loading dynamic correlation data...
[12:05:53.2296839] > [Error] Unhandled exception in RatScanner v2.2.1.0
 -------------------- 
 System.IO.IOException: The process cannot access the file 'C:\Users\shaun\AppData\Local\Temp\Battlestate Games\EscapeFromTarkov\Icon Cache\index.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at RatScanner.IconManager.LoadDynamicCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
</details>

**Comment by Blightbuster** [comment]
Please see #19 

Thanks for submitting though 👍
