### ISSUE TITLE
Could not find icon folder at: C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\bin\Debug\netcoreapp3.1\Data\name

### ISSUE THREAD

**Issue by mitchross** [Blightbuster/RatScanner#27]
**Error**
Could not find icon folder at: C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\bin\Debug\netcoreapp3.1\Data\name
<details>
<summary>Log</summary>

```
[15:25:52.8012426] > [Info]  ----- RatScanner 2.2.1 -----
[15:25:52.8093836] > [Info]  Starting RatScanner...
[15:25:52.8170208] > [Info]  Loading config...
[15:25:52.8561563] > [Info]  Loading price data...
[15:25:53.3465266] > [Info]  Setting default item...
[15:25:53.3586136] > [Info]  Initializing name scan...
[15:25:53.3649040] > [Info]  Loading OCR data...
[15:25:53.4358175] > [Info]  Initializing icon scan...
[15:25:53.4475706] > [Info]  Loading static icons...
[15:25:53.4913945] > [Error] Could not find icon folder at: C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\bin\Debug\netcoreapp3.1\Data\name
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e) in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\Logger.cs:line 32
   at RatScanner.IconManager.LoadStaticIcons() in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\IconManager.cs:line 107
   at RatScanner.IconManager.Init() in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\IconManager.cs:line 90
   at RatScanner.Scan.ItemIconScan.Init() in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\Scan\ItemIconScan.cs:line 32
   at RatScanner.RatScannerMain..ctor() in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\RatScannerMain.cs:line 68
   at RatScanner.RatScannerMain.get_Instance() in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\RatScannerMain.cs:line 17
   at RatScanner.View.MainMenu..ctor() in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\View\MainMenu.xaml.cs:line 17
   at RatScanner.PageSwitcher..ctor() in C:\Users\vanillax\Downloads\RatScanner-master\RatScanner-master\RatScanner\PageSwitcher.xaml.cs:line 31
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at RatScanner.App.Main()
```
</details>

**Comment by Blightbuster** [comment]
Hey, it looks like your trying to build the project from scratch, instead of using the precompiled binary, is this correct?

If it is, you should read this part of the readme:
https://github.com/Blightbuster/RatScanner#setting-up-the-repository

In detail:
> Copy the `name` folder and the `correlation.json` from the [EfT-Icons](https://github.com/Blightbuster/EfTIcons) repository inside `RatScanner\Data\`

**Comment by Blightbuster** [comment]
Please re-open this issue if you still need additional help
