### ISSUE TITLE
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by jmlemetayer** [Blightbuster/RatScanner#28]
**Error**
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
```
System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.text_OCRTesseract_create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode, IntPtr& returnValue)
   at OpenCvSharp.Text.OCRTesseract.Create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode)
   at RatScanner.Scan.ItemNameScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu..ctor()
   at RatScanner.PageSwitcher..ctor()
```
<details>
<summary>Log</summary>

```
[15:26:57.6398876] > [Info]  ----- RatScanner 2.2.1 -----
[15:26:57.6478388] > [Info]  Starting RatScanner...
[15:26:57.6555622] > [Info]  Loading config...
[15:26:57.6821650] > [Info]  Loading price data...
[15:26:58.3780528] > [Info]  Setting default item...
[15:26:58.3967328] > [Info]  Initializing name scan...
[15:26:58.4040895] > [Info]  Loading OCR data...
[15:26:58.4414434] > [Error] The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 -------------------- 
 System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.text_OCRTesseract_create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode, IntPtr& returnValue)
   at OpenCvSharp.Text.OCRTesseract.Create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode)
   at RatScanner.Scan.ItemNameScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu..ctor()
   at RatScanner.PageSwitcher..ctor()
```
</details>

**Comment by Blightbuster** [comment]
Are you trying to compile the project yourself?

The folder should look like this after compiling / extracting the compiled version:
![image](https://user-images.githubusercontent.com/24388294/95099888-c5020280-0730-11eb-82a0-4806b3ae512a.png)

Is your folder missing the OpenCvSharpExtern.dll?

**Comment by jmlemetayer** [comment]
I just follow the [readme](https://github.com/Blightbuster/RatScanner#download) and download [this file](https://github.com/Blightbuster/RatScanner/releases/latest/download/RatScanner.zip)

Then I have install the .Net core runtime and run the RatScanner.exe

![image](https://user-images.githubusercontent.com/1167889/95101592-9dac3500-0732-11eb-9af4-99f2d8de04de.png)

The needed dll seems to be here.

**Comment by jmlemetayer** [comment]
I also try to restart my pc (because of the .NET core installation). But I still have the issue.

**Comment by Blightbuster** [comment]
Hmm as a wild guess, please try to install the .Net Framework additionally.
https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

**Comment by Blightbuster** [comment]
Oops didnt meant to do this...

**Comment by jmlemetayer** [comment]
```
.NET Framework 4.8 or a later update is already installed on this computer.
```
:confused:

**Comment by jmlemetayer** [comment]
For your information, I don't dev on windows. It is just a gaming PC.

I reinstall windows 10 recently from scratch and only install some games (and graphics drivers).

**Comment by Blightbuster** [comment]
Ok could you please download:
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

and do the following:
1. Start Procmon64.exe
2. When it asks you for a filter configure it like this and click `Add` followed by `Apply`
![image](https://user-images.githubusercontent.com/24388294/95125622-83d01980-0755-11eb-9d19-1ece502a40b1.png)
3. Configure the toolbar to look like this:
![image](https://user-images.githubusercontent.com/24388294/95125798-c72a8800-0755-11eb-9454-325835231ade.png)
4. Start RatScanner.exe and wait for the error to happen
5. Once RatScanner is crashed you can close it
6. Inside procmon go to File -> Save and save it on your disk
![image](https://user-images.githubusercontent.com/24388294/95126066-27212e80-0756-11eb-94c8-9f5302bc82de.png)
7. Upload the file somewhere and provide me with the link to it ( Discord DM would be easiest I guess )

https://discord.gg/rdJQTP

**Comment by kokarn** [comment]
Got the exact same error today downloading.
Followed your steps and sent you a dump on Discord

**Error**
The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
```
System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.text_OCRTesseract_create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode, IntPtr& returnValue)
   at OpenCvSharp.Text.OCRTesseract.Create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode)
   at RatScanner.Scan.ItemNameScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu..ctor()
   at RatScanner.PageSwitcher..ctor()
```
<details>
<summary>Log</summary>

```
[13:52:06.6543481] > [Info]  ----- RatScanner 2.3.1 -----
[13:52:06.6648361] > [Info]  Starting RatScanner...
[13:52:06.6713547] > [Info]  Loading config...
[13:52:06.6958168] > [Info]  Loading price data...
[13:52:07.3998185] > [Info]  Setting default item...
[13:52:07.4318477] > [Info]  Initializing name scan...
[13:52:07.4382448] > [Info]  Loading OCR data...
[13:52:07.4654881] > [Error] The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 -------------------- 
 System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.text_OCRTesseract_create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode, IntPtr& returnValue)
   at OpenCvSharp.Text.OCRTesseract.Create(String datapath, String language, String charWhitelist, Int32 oem, Int32 psmode)
   at RatScanner.Scan.ItemNameScan.Init()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.MainMenu..ctor()
   at RatScanner.PageSwitcher..ctor()
```
</details>

**Comment by jmlemetayer** [comment]
So I think I know why it doesn't work.

Recently I bought a new PC and reinstall everything including windows. And instead of installing "windows 10 PRO N" like I did last time, I select "windows 10 PRO".

And it is working now :sunglasses:

@kokarn What is your windows version ?

**Comment by kokarn** [comment]
I'm running Windows 10 Pro N as well, so yeah, that might be the issue!

**Comment by kokarn** [comment]
I've solved this. It's missing Windows Media Features. Here's how to install it on N
https://support.microsoft.com/en-us/help/4475817/media-feature-pack-for-windows-10-n-may-2019

**Comment by Blightbuster** [comment]
Thanks! I'll add this to the FAQ. I really appreciate your work on this issue. ❤️
