### ISSUE TITLE
[Error] Unhandled exception in RatScanner 2.2.2

### ISSUE THREAD

**Issue by chrischristieGWB** [Blightbuster/RatScanner#32]
[11:00:59.0664168] > [Error] Unhandled exception in RatScanner 2.2.2
 -------------------- 
 System.IO.IOException: The process cannot access the file 'C:\Battlestate Games\EFT (live)\Rat Scanner\Log.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.AppendAllText(String path, String contents, Encoding encoding)
   at RatScanner.Logger.AppendToLog(String content)
   at RatScanner.IconManager.LoadDynamicCorrelationData(Int32 retryIndex)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Blightbuster** [comment]
Is it possible that you still have another rat scanner instance open in the background?

**Comment by chrischristieGWB** [comment]
I mean I suppose that's _possible_, but I'm like 99% sure that I didn't have two open at once. I haven't started it back up again since I posted this and it isn't running. Would they have both crashed?

**Comment by Blightbuster** [comment]
No only one of them which tried to access the log file while the other one was writing. But it can well be an issue with the Logger I made since its accessed from multiple threads. I'll label this as a bug and rewrite the Logger to make sure this cant happend with only a single instance running.
