### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dartonias** [Blightbuster/RatScanner#35]
Opened app, was not actively using it, simply browsing my inventory, and then it crashed with this report.

**Error**
Unhandled exception in RatScanner 2.3.0
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at RatScanner.IconManager.InverseCorrelationData()
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
<details>
<summary>Log</summary>

```
[19:45:30.7124004] > [Info]  ----- RatScanner 2.3.0 -----
[19:45:30.7194004] > [Info]  Starting RatScanner...
[19:45:30.7234004] > [Info]  Loading config...
[19:45:30.8454004] > [Info]  Loading price data...
[19:45:31.4334004] > [Info]  Setting default item...
[19:45:31.4454004] > [Info]  Initializing name scan...
[19:45:31.4514004] > [Info]  Loading OCR data...
[19:45:31.7454004] > [Info]  Initializing icon scan...
[19:45:31.7514004] > [Info]  Loading static icons...
[19:45:33.3244004] > [Info]  Loaded 1141/1141 icons successfully.
[19:45:33.3314004] > [Info]  Loading static correlation data...
[19:45:33.3594004] > [Info]  Loading dynamic correlation data...
[19:45:33.3814004] > [Info]  Loading dynamic icons...
[19:45:33.4374004] > [Info]  Loaded 345/345 icons successfully.
[19:45:33.4454004] > [Info]  I

**Comment by Blightbuster** [comment]
Can you reproduce this? I just tried furiously clicking in my inventory and loading all sorts of new items but didnt manage to crash it...

**Comment by dartonias** [comment]
The bug only happened once and I restarted the software after and it did not happen again. The crash prompted a dump here which is why I reported it, but besides managing my stash and hideout, I wasn't doing anything specific that I can report.

**Comment by Blightbuster** [comment]
Ok thanks for getting back on it.
I will close this issue. Please re-open it if you encouter it again. 👍
