### ISSUE TITLE
Could not find icon folder at: C:\Users\dimka\Desktop\RatScanner-master\RatScanner\bin\Debug\netcoreapp3.1\Data\name

### ISSUE THREAD

**Issue by FADelto** [Blightbuster/RatScanner#40]
**Error**
Could not find icon folder at: C:\Users\dimka\Desktop\RatScanner-master\RatScanner\bin\Debug\netcoreapp3.1\Data\name
<details>
<summary>Log</summary>

```
[23:14:22.4926666] > [Info]  ----- RatScanner 2.3.1 -----
[23:14:22.4986390] > [Info]  Starting RatScanner...
[23:14:22.5046934] > [Info]  Loading config...
[23:14:22.5226119] > [Info]  Loading price data...
[23:14:23.3195370] > [Info]  Setting default item...
[23:14:23.3280651] > [Info]  Initializing name scan...
[23:14:23.3317409] > [Info]  Loading OCR data...
[23:14:23.4028456] > [Info]  Initializing icon scan...
[23:14:23.4089949] > [Info]  Loading static icons...
[23:14:23.4247078] > [Error] Could not find icon folder at: C:\Users\dimka\Desktop\RatScanner-master\RatScanner\bin\Debug\netcoreapp3.1\Data\name
 -------------------- 
    at System.Environment.get_StackTrace()
   at RatScanner.Logger.LogError(String message, Exception e) in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\Logger.cs:line 35
   at RatScanner.IconManager.LoadStaticIcons() in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\IconManager.cs:line 111
   at RatScanner.IconManager.Init() in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\IconManager.cs:line 94
   at RatScanner.Scan.ItemIconScan.Init() in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\Scan\ItemIconScan.cs:line 32
   at RatScanner.RatScannerMain..ctor() in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\RatScannerMain.cs:line 70
   at RatScanner.RatScannerMain.get_Instance() in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\RatScannerMain.cs:line 19
   at RatScanner.View.MainMenu..ctor() in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\View\MainMenu.xaml.cs:line 17
   at RatScanner.PageSwitcher..ctor() in C:\Users\dimka\Desktop\RatScanner-master\RatScanner\PageSwitcher.xaml.cs:line 33
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at RatScanner.App.Main()
```
</details>

**Comment by Blightbuster** [comment]
Hey, it looks like you are trying to compile the project yourself. Is this correct?

If you only want to use Rat Scanner, have a look at [this](https://github.com/Blightbuster/RatScanner#download).

If you want to modify the code and contribute to the project however, have a look at [this](https://github.com/Blightbuster/RatScanner#setting-up-the-repository-for-development).

**Comment by FADelto** [comment]
Thanks for help)

**Comment by FADelto** [comment]
> Hey, it looks like you are trying to compile the project yourself. Is this correct?
> 
> If you only want to use Rat Scanner, have a look at [this](https://github.com/Blightbuster/RatScanner#download).
> 
> If you want to modify the code and contribute to the project however, have a look at [this](https://github.com/Blightbuster/RatScanner#setting-up-the-repository-for-development).

Can I get banned for this?

**Comment by Blightbuster** [comment]
If you need further assistance, please re-open this issue.

**Comment by FADelto** [comment]
Can I get banned for this?

**Comment by Blightbuster** [comment]
> > Hey, it looks like you are trying to compile the project yourself. Is this correct?
> > If you only want to use Rat Scanner, have a look at [this](https://github.com/Blightbuster/RatScanner#download).
> > If you want to modify the code and contribute to the project however, have a look at [this](https://github.com/Blightbuster/RatScanner#setting-up-the-repository-for-development).
> 
> Can I get banned for this?

Its currently not approved by BSG. Im trying to get in contact with them since a while now but without much success.

Hence you will have to use it at your own risk for now but as far as I know, no one has been punished for using it yet.

**Comment by FADelto** [comment]
OK, thanks again
